import React, { useMemo, useCallback, useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Platform, Share, ActivityIndicator, ScrollView } from 'react-native';
import { useLocalSearchParams, useRouter, Stack } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Shield, ShieldAlert, ShieldCheck, ShieldQuestion, Copy, Check, Share2, ChevronDown, ChevronUp, ArrowLeft, Clock, Mail, AlertTriangle as AlertTriangleIcon, FileCheck, Scale } from 'lucide-react-native';
import { useQuery } from '@tanstack/react-query';
import * as Haptics from 'expo-haptics';
import * as Clipboard from 'expo-clipboard';
import Colors from '@/constants/colors';
import Logo from '@/components/Logo';
import { resolveShareLink, WalletShareData } from '@/utils/walletShare';
import { fetchMoneyCase } from '@/utils/api';
import type { BadgeType, RailPack, MoneyCaseFullResponse } from '@/types/scan';

const BADGE_MINI: Record<BadgeType | 'UNKNOWN', { color: string; bg: string; Icon: typeof Shield }> = {
  VERIFIED: { color: Colors.verified, bg: Colors.verifiedBg, Icon: ShieldCheck },
  UNVERIFIED: { color: Colors.unverified, bg: Colors.unverifiedBg, Icon: ShieldQuestion },
  HIGH_RISK: { color: Colors.highRisk, bg: Colors.highRiskBg, Icon: ShieldAlert },
  UNKNOWN: { color: Colors.textSecondary, bg: Colors.backgroundTertiary, Icon: Shield },
};

interface TimelineCard {
  id: string;
  day: string;
  dayEs: string;
  titleEn: string;
  titleEs: string;
  iconComponent: typeof Mail;
  iconColor: string;
  templateKey: 'refund' | 'followup' | null;
}

const TIMELINE_CARDS: TimelineCard[] = [
  {
    id: 'day0',
    day: 'Day 0',
    dayEs: 'Día 0',
    titleEn: 'Send Refund Request',
    titleEs: 'Enviar solicitud de reembolso',
    iconComponent: Mail,
    iconColor: Colors.primary,
    templateKey: 'refund',
  },
  {
    id: 'day3',
    day: 'Day +3',
    dayEs: 'Día +3',
    titleEn: 'Send Follow-up',
    titleEs: 'Enviar seguimiento',
    iconComponent: Clock,
    iconColor: Colors.unverified,
    templateKey: 'followup',
  },
  {
    id: 'day7',
    day: 'Day +7',
    dayEs: 'Día +7',
    titleEn: 'Final Notice & Escalate',
    titleEs: 'Aviso final y escalar',
    iconComponent: AlertTriangleIcon,
    iconColor: Colors.highRisk,
    templateKey: null,
  },
  {
    id: 'escalate',
    day: '',
    dayEs: '',
    titleEn: 'Escalation Steps',
    titleEs: 'Pasos de escalación',
    iconComponent: Scale,
    iconColor: Colors.accent,
    templateKey: null,
  },
];

export default function RefundScreen() {
  const { token, caseId, locale: paramLocale } = useLocalSearchParams<{
    token: string;
    caseId: string;
    locale: string;
  }>();
  const router = useRouter();

  const [locale, setLocale] = useState<'en' | 'es'>((paramLocale as 'en' | 'es') || 'en');
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [expandedCards, setExpandedCards] = useState<Record<string, boolean>>({ day0: true });

  const isEs = locale === 'es';

  const shareQuery = useQuery<WalletShareData | null>({
    queryKey: ['share-link', token],
    queryFn: () => resolveShareLink(token || ''),
    enabled: !!token,
    staleTime: 60000,
  });

  const caseQuery = useQuery<MoneyCaseFullResponse | null>({
    queryKey: ['money-case', caseId],
    queryFn: () => fetchMoneyCase(caseId || ''),
    enabled: !!caseId,
    staleTime: 30000,
  });

  const shareData = shareQuery.data;
  const caseData = caseQuery.data;
  const railPack: RailPack | null = caseData?.rail_pack ?? null;

  const badgeKey: BadgeType | 'UNKNOWN' = useMemo(() => {
    if (!shareData?.badge) return 'UNKNOWN';
    return shareData.badge;
  }, [shareData?.badge]);

  const badgeConfig = BADGE_MINI[badgeKey];
  const BadgeIcon = badgeConfig.Icon;

  useEffect(() => {
    if (Platform.OS === 'web') {
      document.title = isEs ? 'Rail Pack - REAiL' : 'Refund Rail Pack - REAiL';
    }
  }, [isEs]);

  const handleCopyText = useCallback(async (text: string, field: string) => {
    try {
      await Clipboard.setStringAsync(text);
      setCopiedField(field);
      if (Platform.OS !== 'web') {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      }
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.log('[Refund] Copy error:', err);
    }
  }, []);

  const handleSharePack = useCallback(async () => {
    if (Platform.OS !== 'web') {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }

    const shareUrl = Platform.OS === 'web'
      ? window.location.href
      : `https://reail.app/s/${token}/refund?caseId=${caseId}`;

    const message = isEs
      ? `Mi Rail Pack de reembolso generado por REAiL: ${shareUrl}`
      : `My refund Rail Pack generated by REAiL: ${shareUrl}`;

    try {
      if (Platform.OS === 'web') {
        if (navigator.share) {
          await navigator.share({ title: 'REAiL Rail Pack', text: message, url: shareUrl });
        } else {
          await navigator.clipboard.writeText(shareUrl);
          setCopiedField('share-url');
          setTimeout(() => setCopiedField(null), 2000);
        }
      } else {
        await Share.share({ message });
      }
    } catch (err) {
      console.log('[Refund] Share error:', err);
    }
  }, [token, caseId, isEs]);

  const toggleCard = useCallback((cardId: string) => {
    if (Platform.OS !== 'web') {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }
    setExpandedCards(prev => ({ ...prev, [cardId]: !prev[cardId] }));
  }, []);

  const isLoading = shareQuery.isLoading || caseQuery.isLoading;

  if (isLoading) {
    return (
      <View style={styles.container}>
        <Stack.Screen options={{ headerShown: false }} />
        <SafeAreaView style={styles.safeArea}>
          <View style={styles.loadingContainer}>
            <Logo size="small" />
            <ActivityIndicator size="large" color={Colors.primary} style={styles.loader} />
            <Text style={styles.loadingText}>
              {isEs ? 'Cargando tu Rail Pack...' : 'Loading your Rail Pack...'}
            </Text>
          </View>
        </SafeAreaView>
      </View>
    );
  }

  if (!railPack) {
    return (
      <View style={styles.container}>
        <Stack.Screen options={{ headerShown: false }} />
        <SafeAreaView style={styles.safeArea}>
          <View style={styles.loadingContainer}>
            <Logo size="small" />
            <FileCheck size={56} color={Colors.textTertiary} style={{ marginTop: 32 }} />
            <Text style={styles.errorTitle}>
              {isEs ? 'Rail Pack no encontrado' : 'Rail Pack Not Found'}
            </Text>
            <Text style={styles.errorSubtext}>
              {isEs
                ? 'Regresa al reporte y genera tu Rail Pack primero.'
                : 'Go back to the report and generate your Rail Pack first.'}
            </Text>
            <TouchableOpacity
              style={styles.backNavButton}
              onPress={() => router.back()}
            >
              <ArrowLeft size={18} color={Colors.text} />
              <Text style={styles.backNavText}>
                {isEs ? 'Volver al reporte' : 'Back to Report'}
              </Text>
            </TouchableOpacity>
          </View>
        </SafeAreaView>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <Stack.Screen options={{ headerShown: false }} />
      <SafeAreaView style={styles.safeArea}>
        <View style={styles.topBar}>
          <TouchableOpacity
            style={styles.topBarBack}
            onPress={() => router.back()}
            testID="refund-back"
          >
            <ArrowLeft size={20} color={Colors.text} />
          </TouchableOpacity>
          <Text style={styles.topBarTitle}>
            {isEs ? 'Tu Rail Pack' : 'Your Rail Pack'}
          </Text>
          <View style={styles.topBarLang}>
            <TouchableOpacity
              style={[styles.langChip, locale === 'en' && styles.langChipActive]}
              onPress={() => setLocale('en')}
            >
              <Text style={[styles.langChipText, locale === 'en' && styles.langChipTextActive]}>EN</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.langChip, locale === 'es' && styles.langChipActive]}
              onPress={() => setLocale('es')}
            >
              <Text style={[styles.langChipText, locale === 'es' && styles.langChipTextActive]}>ES</Text>
            </TouchableOpacity>
          </View>
        </View>

        <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
          {shareData && (
            <View style={styles.verdictStrip}>
              <View style={[styles.verdictBadge, { backgroundColor: badgeConfig.bg }]}>
                <BadgeIcon size={18} color={badgeConfig.color} />
              </View>
              <View style={styles.verdictInfo}>
                <Text style={styles.verdictDomain} numberOfLines={1}>{shareData.domain}</Text>
                {shareData.score !== null && (
                  <Text style={[styles.verdictScore, { color: badgeConfig.color }]}>
                    {isEs ? 'Puntuación' : 'Score'}: {shareData.score}/100
                  </Text>
                )}
              </View>
              {shareData.top_red_flags.length > 0 && (
                <View style={styles.verdictFlagCount}>
                  <Text style={styles.verdictFlagCountText}>{shareData.top_red_flags.length}</Text>
                  <Text style={styles.verdictFlagLabel}>{isEs ? 'alertas' : 'flags'}</Text>
                </View>
              )}
            </View>
          )}

          <View style={styles.content}>
            <View style={styles.sectionHeader}>
              <Clock size={16} color={Colors.accent} />
              <Text style={styles.sectionTitle}>
                {isEs ? 'Línea de tiempo de reembolso' : 'Refund Timeline'}
              </Text>
            </View>

            {TIMELINE_CARDS.map((card, idx) => {
              const isExpanded = !!expandedCards[card.id];
              const CardIcon = card.iconComponent;
              const isLast = idx === TIMELINE_CARDS.length - 1;

              return (
                <View key={card.id} style={styles.timelineItem}>
                  <View style={styles.timelineLine}>
                    <View style={[styles.timelineDot, { backgroundColor: card.iconColor }]} />
                    {!isLast && <View style={styles.timelineConnector} />}
                  </View>

                  <View style={[styles.timelineCard, isExpanded && styles.timelineCardExpanded]}>
                    <TouchableOpacity
                      style={styles.timelineCardHeader}
                      onPress={() => toggleCard(card.id)}
                      activeOpacity={0.7}
                      testID={`timeline-${card.id}`}
                    >
                      <CardIcon size={20} color={card.iconColor} />
                      <View style={styles.timelineCardTitleArea}>
                        {(card.day || card.dayEs) ? (
                          <Text style={[styles.timelineDay, { color: card.iconColor }]}>
                            {isEs ? card.dayEs : card.day}
                          </Text>
                        ) : null}
                        <Text style={styles.timelineCardTitle}>
                          {isEs ? card.titleEs : card.titleEn}
                        </Text>
                      </View>
                      {isExpanded
                        ? <ChevronUp size={18} color={Colors.textTertiary} />
                        : <ChevronDown size={18} color={Colors.textTertiary} />
                      }
                    </TouchableOpacity>

                    {isExpanded && (
                      <View style={styles.timelineCardBody}>
                        {card.id === 'day0' && (
                          <>
                            <Text style={styles.cardInstructions}>
                              {isEs
                                ? 'Copia y envía esta plantilla al servicio al cliente del comercio por email o formulario web.'
                                : 'Copy and send this template to the merchant\'s customer service via email or web form.'}
                            </Text>
                            <View style={styles.templateContainer}>
                              <View style={styles.templateHeader}>
                                <Text style={styles.templateLabel}>
                                  {isEs ? 'Plantilla de solicitud' : 'Refund Request'}
                                </Text>
                                <TouchableOpacity
                                  style={styles.copyBtn}
                                  onPress={() => handleCopyText(railPack.refund_request_template, 'refund')}
                                  testID="copy-refund"
                                >
                                  {copiedField === 'refund' ? (
                                    <Check size={16} color={Colors.verified} />
                                  ) : (
                                    <Copy size={16} color={Colors.primary} />
                                  )}
                                  <Text style={[styles.copyBtnText, copiedField === 'refund' && { color: Colors.verified }]}>
                                    {copiedField === 'refund' ? (isEs ? 'Copiado' : 'Copied') : (isEs ? 'Copiar' : 'Copy')}
                                  </Text>
                                </TouchableOpacity>
                              </View>
                              <Text style={styles.templateText} selectable>{railPack.refund_request_template}</Text>
                            </View>
                          </>
                        )}

                        {card.id === 'day3' && (
                          <>
                            <Text style={styles.cardInstructions}>
                              {isEs
                                ? 'Si no has recibido respuesta en 3 días hábiles, envía este seguimiento.'
                                : 'If you haven\'t received a response within 3 business days, send this follow-up.'}
                            </Text>
                            <View style={styles.templateContainer}>
                              <View style={styles.templateHeader}>
                                <Text style={styles.templateLabel}>
                                  {isEs ? 'Plantilla de seguimiento' : 'Follow-up Template'}
                                </Text>
                                <TouchableOpacity
                                  style={styles.copyBtn}
                                  onPress={() => handleCopyText(railPack.follow_up_template, 'followup')}
                                  testID="copy-followup"
                                >
                                  {copiedField === 'followup' ? (
                                    <Check size={16} color={Colors.verified} />
                                  ) : (
                                    <Copy size={16} color={Colors.primary} />
                                  )}
                                  <Text style={[styles.copyBtnText, copiedField === 'followup' && { color: Colors.verified }]}>
                                    {copiedField === 'followup' ? (isEs ? 'Copiado' : 'Copied') : (isEs ? 'Copiar' : 'Copy')}
                                  </Text>
                                </TouchableOpacity>
                              </View>
                              <Text style={styles.templateText} selectable>{railPack.follow_up_template}</Text>
                            </View>
                          </>
                        )}

                        {card.id === 'day7' && (
                          <>
                            <Text style={styles.cardInstructions}>
                              {isEs
                                ? 'Sin respuesta después de 7 días: es hora de escalar. Reenvía la plantilla de seguimiento con un aviso final y procede con los pasos de escalación.'
                                : 'No response after 7 days: time to escalate. Re-send the follow-up template with a final notice and proceed with escalation steps below.'}
                            </Text>
                            <TouchableOpacity
                              style={styles.copyBtn}
                              onPress={() => handleCopyText(railPack.follow_up_template, 'final')}
                            >
                              {copiedField === 'final' ? (
                                <Check size={16} color={Colors.verified} />
                              ) : (
                                <Copy size={16} color={Colors.primary} />
                              )}
                              <Text style={[styles.copyBtnText, copiedField === 'final' && { color: Colors.verified }]}>
                                {copiedField === 'final'
                                  ? (isEs ? 'Copiado' : 'Copied')
                                  : (isEs ? 'Copiar plantilla de seguimiento' : 'Copy follow-up template')}
                              </Text>
                            </TouchableOpacity>
                          </>
                        )}

                        {card.id === 'escalate' && (
                          <>
                            <View style={styles.checklistContainer}>
                              {railPack.escalation_checklist.map((item, i) => (
                                <Text key={i} style={styles.checklistItem}>{item}</Text>
                              ))}
                            </View>
                          </>
                        )}
                      </View>
                    )}
                  </View>
                </View>
              );
            })}

            <View style={styles.sectionHeader}>
              <FileCheck size={16} color={Colors.accent} />
              <Text style={styles.sectionTitle}>
                {isEs ? 'Checklist de evidencia' : 'Evidence Checklist'}
              </Text>
            </View>
            <View style={styles.evidenceCard}>
              {railPack.evidence_checklist.map((item, idx) => (
                <Text key={idx} style={styles.evidenceItem}>{item}</Text>
              ))}
            </View>

            <TouchableOpacity
              style={styles.sharePackButton}
              onPress={handleSharePack}
              activeOpacity={0.85}
              testID="share-pack-btn"
            >
              <Share2 size={20} color={Colors.text} />
              <Text style={styles.sharePackText}>
                {copiedField === 'share-url'
                  ? (isEs ? 'Enlace copiado' : 'Link Copied')
                  : (isEs ? 'Compartir Rail Pack' : 'Share Rail Pack')}
              </Text>
            </TouchableOpacity>

            <View style={styles.disclaimerBox}>
              <Text style={styles.disclaimerTitle}>
                {isEs ? 'Aviso legal' : 'Legal Disclaimer'}
              </Text>
              <Text style={styles.disclaimerText}>{railPack.disclaimer}</Text>
            </View>

            <View style={styles.footerArea}>
              <Text style={styles.footerText}>Powered by REAiL Systems</Text>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  loader: {
    marginTop: 32,
  },
  loadingText: {
    fontSize: 16,
    color: Colors.textSecondary,
    marginTop: 16,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: Colors.text,
    marginTop: 16,
    textAlign: 'center',
  },
  errorSubtext: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 20,
  },
  backNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 24,
  },
  backNavText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  topBarBack: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700' as const,
    color: Colors.text,
    textAlign: 'center',
  },
  topBarLang: {
    flexDirection: 'row',
    backgroundColor: Colors.backgroundTertiary,
    borderRadius: 6,
    padding: 2,
  },
  langChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
  },
  langChipActive: {
    backgroundColor: Colors.primary,
  },
  langChipText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: Colors.textTertiary,
  },
  langChipTextActive: {
    color: Colors.text,
  },
  verdictStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: Colors.card,
    borderBottomWidth: 1,
    borderBottomColor: Colors.cardBorder,
    gap: 12,
  },
  verdictBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verdictInfo: {
    flex: 1,
  },
  verdictDomain: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
  },
  verdictScore: {
    fontSize: 12,
    fontWeight: '500' as const,
    marginTop: 2,
  },
  verdictFlagCount: {
    alignItems: 'center',
    backgroundColor: Colors.highRiskBg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  verdictFlagCountText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: Colors.highRisk,
  },
  verdictFlagLabel: {
    fontSize: 9,
    color: Colors.highRisk,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.text,
    letterSpacing: 0.3,
  },
  timelineItem: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  timelineLine: {
    width: 24,
    alignItems: 'center',
    paddingTop: 4,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  timelineConnector: {
    width: 2,
    flex: 1,
    backgroundColor: Colors.border,
    marginTop: 4,
  },
  timelineCard: {
    flex: 1,
    backgroundColor: Colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    marginLeft: 8,
    marginBottom: 10,
    overflow: 'hidden',
  },
  timelineCardExpanded: {
    borderColor: Colors.primary + '40',
  },
  timelineCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 10,
  },
  timelineCardTitleArea: {
    flex: 1,
  },
  timelineDay: {
    fontSize: 11,
    fontWeight: '700' as const,
    letterSpacing: 0.5,
    textTransform: 'uppercase' as const,
    marginBottom: 2,
  },
  timelineCardTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: Colors.text,
  },
  timelineCardBody: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 12,
  },
  cardInstructions: {
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 19,
    marginBottom: 12,
  },
  templateContainer: {
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  templateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.backgroundTertiary,
  },
  templateLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  copyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  copyBtnText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.primary,
  },
  templateText: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 18,
    padding: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  checklistContainer: {
    gap: 6,
  },
  checklistItem: {
    fontSize: 13,
    color: Colors.text,
    lineHeight: 22,
  },
  evidenceCard: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    padding: 14,
    gap: 6,
    marginBottom: 20,
  },
  evidenceItem: {
    fontSize: 13,
    color: Colors.text,
    lineHeight: 22,
  },
  sharePackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: Colors.primary,
    height: 52,
    borderRadius: 14,
    marginBottom: 16,
  },
  sharePackText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: Colors.text,
  },
  disclaimerBox: {
    backgroundColor: Colors.backgroundTertiary,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  disclaimerTitle: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textTertiary,
    marginBottom: 6,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  disclaimerText: {
    fontSize: 11,
    color: Colors.textTertiary,
    lineHeight: 16,
  },
  footerArea: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  footerText: {
    fontSize: 12,
    color: Colors.textTertiary,
  },
});
